openapi: 3.0.0
info:
  title: "API"
  version: "1.0.0"
servers:
  - url: 'https://api.server.test/v1'
    description: Server description
  - url: 'https://localhost:8000/v1'
    description: Local host

components:
  schemas:
    car:
      type: object
      required:
        - id
        - name
        - owner_id
        - date_created
        - price_per_day
        - location
      properties:
        id:
          type: string
        name:
          type: string
        booked:
          type: boolean
          description: "determines if the car is booked or not"
        owner_id:
          type: string
        date_created:
          type: integer
        price_per_day:
          type: number
        price_per_month:
          type: number
        location:
          type: object
          description: |
            place where the car is located 
            together with its latitude and longitude
          required:
            - lat
            - long
            - place_name
          properties:
            lat:
              type: number
            long:
              type: number
            place_name:
              type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


paths:
  "/users":
        post:
            tags:
                - users
            requestBody:
             content:
              application/json:
                  schema:
                    type: object
                    required:
                        - email
                        - name
                        - password
                    properties:
                        email:
                            type: string
                        name:
                            type: string
                        password:
                            type: string
            responses:
                201:
                    description: "Success"
                400:
                    description: "Bad request"
                500:
                    description: "Internal Server Error"

        get:
            tags:
                - users
            responses:
                200:
                    description: "Success"
                400:
                    description: "Bad request"
                500:
                    description: "Internal Server Error"

  "/users/{user_id}":
        get:
            tags:
                - users
            parameters:
                - in: path
                  name: user_id
                  required: true
                  schema:
                    type: string

            responses:
                200:
                    description: "A single user"
                404:
                    description: "User not found"
                400:
                    description: "Bad request"
                500:
                    description: "Internal Server Error"

        patch:
            tags:
                - users
            parameters:
                - in: path
                  name: user_id
                  required: true
                  schema:
                   type: string

            requestBody:
              content:
                  application/json:
                   schema:
                    type: object
                    properties:
                        name:
                            type: string
                        
            responses:
                200:
                    description: "Success"
                404:
                    description: "User not found"
                400:
                    description: "Bad request"
                500:
                    description: "Internal Server Error"

        delete:
            tags:
                - users
            parameters:
                - in: path
                  name: user_id
                  required: true
                  schema:
                   type: string

            responses:
                200:
                    description: "Success"
                404:
                    description: "User not found"
                400:
                    description: "Bad request"
                500:
                    description: "Internal Server Error"


  "/users/login":
        post:
            tags:
                - users
            requestBody:
              content:
                  application/json:
                    schema:
                     type: object
                     required:
                        - email
                        - password
                     properties:
                        email:
                            type: string
                        password:
                            type: string
            responses:
                200:
                    description: "success"
                400:
                    description: "bad request"
                401:
                    description: "failed login"

  "/users/admin_login":
        post:
            tags:
                - users
            requestBody:
              content:
                  application/json:
                   schema:
                    type: object
                    required:
                        - email
                        - password
                    properties:
                        email:
                            type: string
                        password:
                            type: string

            responses:
                200:
                    description: "success"
                400:
                    description: "bad request"
                401:
                    description: "failed login"

  "/users/verify":
        post:
            tags:
                - auth
                - users
            requestBody:
              content:
                  application/json:
                   schema:
                    type: object
                    required:
                        - email
                    properties:
                        email:
                            type: string

            responses:

                200:
                    description: "Success"
                400:
                    description: "Bad request"
                404:
                    description: "User not found"
                500:
                    description: "Internal Server Error"

  "/users/verify/{token}":
        get:
            tags:
                - auth
                - users
            parameters:
                - in: path
                  name: token
                  required: true
                  schema:
                   type: string
            responses:
                200:
                    description: "Success"
                404:
                    description: "User not found"
                400:
                    description: "Bad request"
                500:
                    description: "Internal Server Error"

  "/users/forgot_password":
        post:
            tags:
                - users
                - auth
            requestBody:
              content:
                  application/json:
                   schema:
                    type: object
                    required:
                        - email
                    properties:
                        email:
                            type: string
            responses:
                200:
                    description: "Success"
                400:
                    description: "Bad request"
                404:
                    description: "User not found"
                500:
                    description: "Internal Server Error"

  "/users/reset_password/{token}":
        post:
            tags:
                - users
                - auth
            parameters:
                - in: path
                  name: token
                  required: true
                  schema:
                   type: string
            requestBody:
              content:
                  application/json:
                   schema:
                    type: object
                    required:
                        - password
                    properties:
                        password:
                            type: string
            responses:
                200:
                    description: "Success"
                400:
                    description: "Bad request"
                404:
                    description: "User not found"
                500:
                    description: "Internal Server Error"
            
  "/users/{user_id}/cars":
        get:
            tags:
                - user cars
            security:
             - bearerAuth: []
            parameters:
                - in: header
                  name: Authorization
                  required: true
                - in: path
                  name: user_id
                  required: true
                  schema:
                  type: string
            responses:
                200:
                    description: "Success"
                404:
                    description: "User not found"
                400:
                    description: "Bad request"
                500:
                    description: "Internal Server Error"
    
  /car_booking/request-to-book:
    post:
      tags:
          - "car booking"    
      summary:  request to book a car
      requestBody:
       content:
           application/json:
            schema:
             type: object
             required:
              - user_id
              - car_id
             properties:
              user_id:
               type: string
              car_id:
               type: string
      responses:
        '200':
          description: OK
  /car_booking/{booking_request_id}/{status}:
    patch:
      tags:
          - "car booking"    
      summary:  accept,decline,cancel a car booking request
      parameters:
          - in: path
            name: status
            required: true
            schema:
             type: string
             enum:
                 - accept
                 - decline
                 - cancel
      responses:
        '200':
          description: OK
  /car_booking/{booking_request_id}:
    get:
      tags:
          - "car booking"    
      summary: get details of a car booking request
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                  car_id:
                    type: string
                  date_created:
                    type: string
                  date_updated:
                    type: string
                  date_started:
                    type: string
                  date_ending:
                    type: string
                  status:
                    type: string
                    enum: [pending, accepted, declined, canceled]
    patch:
      tags:
          - "car booking"    
      summary: update a booking request
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                  car_id:
                    type: string
                  date_created:
                    type: string
                  date_updated:
                    type: string
                  status:
                    type: string
                    enum: [pending, accepted, declined, canceled]
  /car_booking:
    description: car booking endpoint
    get:
      tags:
          - "car booking"
      summary:  Get all booking requests
      parameters:
        - name: query
          description: Search for booking requests
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK

    post:
      tags:
          - "car booking"
      summary:  Add a new booking request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - car_id
                - user_id
              properties:
                car_id:
                  type: string
                user_id:
                  type: string

      responses:
        "200":
          description: OK


  /cars/{car_id}:
    get:
      tags:
        - "cars"
      description: retrieve information for aparticular car
      parameters:
        - name: car_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "a cars information"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/car"
        "404":
          description: Not found

    patch:
      tags:
        - "cars"
      description: Update an existing car
      parameters:
        - name: car_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/car"
      responses:
        "200":
          description: "a cars information"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/car"

    delete:
      tags:
        - "cars"
      description: delete an existing car
      parameters:
        - name: car_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "success"
        "404":
          description: "Not found"

  /cars:
    get:
      tags:
        - "cars"
      description: search for listed cars
      parameters:
        - name: query
          description: "search using a keyword"
          in: query
          schema:
            type: string
          required: false
      responses:
        "200":
          description: cars matching the query or a paginated list of cars if no query is provided
          content:
            application/json: #response body media type
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/car"

    post:
      tags:
        - "cars"
      description: Add a new car to the listed cars
      requestBody:
        description: "a cars information"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/car"
      responses:
        "200":
          description: Returns the newly added car
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/car"

  /:
    get:
      description: returns api docs
      responses:
        "200":
          description: OK



